VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IWebElement"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Sub SetText(text As String)

End Sub

Public Sub SetTextContent(text As String)

End Sub

Public Sub Click()

End Sub

Public Sub SelectItemByText(text As String)

End Sub


